"""Generate __device__ lookup tables for bposit16 → bposit16 transcendental
functions, baked from the validated Python reference (bposit16_reference.py).

Output: bposit16_luts.cuh — a header included by shannon_entropy_bposit16.cu.

The LUTs (each 65536 entries × 2 bytes = 128 KB) live in __device__ const
memory; texture caching covers the read pattern. Constant memory is only
64 KB total which doesn't fit one full LUT, hence __device__ const.

Tables emitted:
    log2_lut[65536]   — bposit16(log₂(bposit16_decode(i)))
                        i for which decoded value <= 0 maps to NAR (0x8000)
"""
from __future__ import annotations
import sys
from pathlib import Path

# Import the reference impl
sys.path.insert(0, str(Path(__file__).parent))
from bposit16_reference import (  # noqa: E402
    NAR, ZERO, ONE, QUIRE_FRAC_BITS, decode_bposit16, decoded_to_fraction,
    encode_bposit16, bposit16_log2 as py_bposit16_log2,
    bposit16_mul as py_bposit16_mul,
    bposit16_to_quire as py_bposit16_to_quire,
)
import math


def main() -> None:
    out_path = Path(__file__).parent / "bposit16_luts.cuh"
    log2_lut = []
    n_special = 0
    n_negative = 0
    n_valid = 0
    for i in range(65536):
        d = decode_bposit16(i)
        if d.is_special:
            log2_lut.append(NAR)
            n_special += 1
            continue
        try:
            f = decoded_to_fraction(d)
        except ValueError:
            log2_lut.append(NAR)
            n_special += 1
            continue
        if f <= 0:
            log2_lut.append(NAR)
            n_negative += 1
            continue
        try:
            log_val = math.log2(float(f))
        except (ValueError, OverflowError):
            log2_lut.append(NAR)
            n_special += 1
            continue
        log2_lut.append(encode_bposit16(log_val))
        n_valid += 1

    lines = [
        "// Auto-generated by deploy/5dst_cuda/build_bposit_luts.py",
        "// DO NOT EDIT — regenerate with `python build_bposit_luts.py`.",
        "//",
        f"// Stats: valid={n_valid}, negative_or_zero={n_negative}, special={n_special}",
        "",
        "#ifndef MOSYNE_BPOSIT16_LUTS_CUH",
        "#define MOSYNE_BPOSIT16_LUTS_CUH",
        "",
        "#include <cstdint>",
        "",
        "// log₂ LUT: log2_lut[bposit16_bits_in] = bposit16_bits_out",
        "// 65536 × 2 bytes = 128 KB. __device__ const so it lands in global",
        "// memory but L2-caches well due to spatial locality of probability",
        "// values clustering near canonical encodings (0x3800 = 0.25, etc.).",
        "__device__ const std::uint16_t bposit16_log2_lut_first_half[32768] = {",
    ]
    # First 32K entries (fits in __constant__ memory's 64 KB budget)
    for chunk_start in range(0, 32768, 16):
        chunk = log2_lut[chunk_start : chunk_start + 16]
        lines.append("    " + ", ".join(f"0x{v:04x}" for v in chunk) + ",")
    lines.append("};")
    lines.append("")
    lines.append(
        "__device__ const std::uint16_t bposit16_log2_lut_second_half[32768] = {"
    )
    for chunk_start in range(32768, 65536, 16):
        chunk = log2_lut[chunk_start : chunk_start + 16]
        lines.append("    " + ", ".join(f"0x{v:04x}" for v in chunk) + ",")
    lines.append("};")
    lines.append("")
    lines.append("__device__ __forceinline__")
    lines.append("std::uint16_t bposit16_log2_lookup(std::uint16_t x) {")
    lines.append("    return (x < 32768)")
    lines.append("        ? bposit16_log2_lut_first_half[x]")
    lines.append("        : bposit16_log2_lut_second_half[x - 32768];")
    lines.append("}")
    lines.append("")

    # ---- TERM LUT: p · log₂(p) precomputed ---------------------------------
    # 65 536 entries × 2 bytes = 128 KB. Half in __constant__, half in __device__.
    term_lut = []
    for i in range(65536):
        lp = py_bposit16_log2(i)
        if lp == NAR:
            term_lut.append(NAR)
            continue
        term_lut.append(py_bposit16_mul(i, lp))

    lines.append("// Term LUT: term_lut[p] = bposit16(p · log₂(p))")
    lines.append("__device__ const std::uint16_t bposit16_term_lut_first_half[32768] = {")
    for chunk_start in range(0, 32768, 16):
        chunk = term_lut[chunk_start : chunk_start + 16]
        lines.append("    " + ", ".join(f"0x{v:04x}" for v in chunk) + ",")
    lines.append("};")
    lines.append("")
    lines.append("__device__ const std::uint16_t bposit16_term_lut_second_half[32768] = {")
    for chunk_start in range(32768, 65536, 16):
        chunk = term_lut[chunk_start : chunk_start + 16]
        lines.append("    " + ", ".join(f"0x{v:04x}" for v in chunk) + ",")
    lines.append("};")
    lines.append("")
    lines.append("__device__ __forceinline__")
    lines.append("std::uint16_t bposit16_term_lookup(std::uint16_t x) {")
    lines.append("    return (x < 32768)")
    lines.append("        ? bposit16_term_lut_first_half[x]")
    lines.append("        : bposit16_term_lut_second_half[x - 32768];")
    lines.append("}")
    lines.append("")

    # ---- TO-QUIRE LUT: each bposit16 → 256-bit signed fixed-point (4× uint64) -
    # 65 536 × 32 bytes = 2 MB. Lives in __device__ const memory.
    # quire256 has QUIRE_FRAC_BITS (96) fraction bits and is signed.
    # We pack as little-endian 4× uint64 (matches the on-GPU quire256 struct).
    to_quire = []
    for i in range(65536):
        q_int = py_bposit16_to_quire(i)  # Python int (arbitrary precision)
        # Convert to 256-bit two's complement representation
        if q_int < 0:
            q_int += (1 << 256)
        words = []
        for w in range(4):
            words.append((q_int >> (64 * w)) & 0xFFFFFFFFFFFFFFFF)
        to_quire.append(tuple(words))

    lines.append("// To-quire LUT: each bposit16 → 4× uint64 (256-bit signed FP, 96 frac bits)")
    lines.append("__device__ const std::uint64_t bposit16_to_quire_lut[65536][4] = {")
    for i, words in enumerate(to_quire):
        lines.append(
            "    {0x{:016x}ull, 0x{:016x}ull, 0x{:016x}ull, 0x{:016x}ull}}, // [{}]"
            .format(words[0], words[1], words[2], words[3], i)
            .replace("}}", "}", 1) if False else
            f"    {{0x{words[0]:016x}ull, 0x{words[1]:016x}ull, 0x{words[2]:016x}ull, 0x{words[3]:016x}ull}},"
        )
    lines.append("};")
    lines.append("")

    # ---- Test-input table: bposit16(1/n) for n in powers of 2 ---------------
    # Lets test_shannon_entropy.cu accept arbitrary n without needing a
    # __device__ encoder. The set of representable uniform sizes is exactly
    # those n for which 1/n is exactly representable in bposit16 — powers of
    # 2 in our case.
    lines.append("// Pre-encoded test inputs: bposit16(1/n) for n = 2^k")
    lines.append("// Used by test_shannon_entropy: input array filled with")
    lines.append("// repeats of bposit16_one_over_2k[k] for k in [1..12].")
    lines.append("__device__ const std::uint16_t bposit16_one_over_2k[16] = {")
    for k in range(16):
        n = 1 << k
        v = encode_bposit16(1.0 / n) if n > 0 else 0
        lines.append(f"    0x{v:04x}, // 1/{n} (k={k}), expected H = log2({n}) = {k}")
    lines.append("};")
    lines.append("")
    # And the host-callable encoder (a C port wouldn't fit cleanly here;
    # for now expose the table and leave full encode for a future tick).

    # ---- BPOSIT16 SQRT LUT (for LQG area_operator + Jacobi eigendecomp) ---
    # sqrt_lut[p] = bposit16(sqrt(decoded_value)). For negative values: NAR.
    # 65 536 × 2 bytes = 128 KB. __device__ const.
    from bposit16_reference import bposit16_sqrt as py_bposit16_sqrt
    sqrt_lut = [py_bposit16_sqrt(i) for i in range(65536)]

    lines.append("// bposit16 √ LUT — sqrt_lut[p] = bposit16(√decoded(p))")
    lines.append("// NaR for negative inputs. Used by LQG area_operator and")
    lines.append("// (eventually) Jacobi eigendecomposition.")
    lines.append("__device__ const std::uint16_t bposit16_sqrt_lut_first_half[32768] = {")
    for chunk_start in range(0, 32768, 16):
        chunk = sqrt_lut[chunk_start:chunk_start + 16]
        lines.append("    " + ", ".join(f"0x{v:04x}" for v in chunk) + ",")
    lines.append("};")
    lines.append("__device__ const std::uint16_t bposit16_sqrt_lut_second_half[32768] = {")
    for chunk_start in range(32768, 65536, 16):
        chunk = sqrt_lut[chunk_start:chunk_start + 16]
        lines.append("    " + ", ".join(f"0x{v:04x}" for v in chunk) + ",")
    lines.append("};")
    lines.append("")
    lines.append("__device__ __forceinline__")
    lines.append("std::uint16_t bposit16_sqrt_lookup(std::uint16_t x) {")
    lines.append("    return (x < 32768)")
    lines.append("        ? bposit16_sqrt_lut_first_half[x]")
    lines.append("        : bposit16_sqrt_lut_second_half[x - 32768];")
    lines.append("}")
    lines.append("")

    # ---- BPOSIT16 RECIPROCAL LUT (for Schwarzschild metric + bposit division)
    # recip_lut[p] = bposit16(1 / decoded(p)). NaR for zero / NaR.
    # 65 536 × 2 bytes = 128 KB. __device__ const.
    from bposit16_reference import bposit16_reciprocal as py_bposit16_recip
    recip_lut = [py_bposit16_recip(i) for i in range(65536)]

    lines.append("// bposit16 reciprocal LUT — recip_lut[p] = bposit16(1/decoded(p))")
    lines.append("// NaR for zero / NaR inputs. Underpins bposit division and the")
    lines.append("// Layer-4 Schwarzschild g_rr = 1/(1 - 2M/r) computation.")
    lines.append("__device__ const std::uint16_t bposit16_recip_lut_first_half[32768] = {")
    for chunk_start in range(0, 32768, 16):
        chunk = recip_lut[chunk_start:chunk_start + 16]
        lines.append("    " + ", ".join(f"0x{v:04x}" for v in chunk) + ",")
    lines.append("};")
    lines.append("__device__ const std::uint16_t bposit16_recip_lut_second_half[32768] = {")
    for chunk_start in range(32768, 65536, 16):
        chunk = recip_lut[chunk_start:chunk_start + 16]
        lines.append("    " + ", ".join(f"0x{v:04x}" for v in chunk) + ",")
    lines.append("};")
    lines.append("")
    lines.append("__device__ __forceinline__")
    lines.append("std::uint16_t bposit16_recip_lookup(std::uint16_t x) {")
    lines.append("    return (x < 32768)")
    lines.append("        ? bposit16_recip_lut_first_half[x]")
    lines.append("        : bposit16_recip_lut_second_half[x - 32768];")
    lines.append("}")
    lines.append("")

    # ---- BPOSIT16 EXP2 LUT (for multiply via mul(a,b) = exp2(log2(a)+log2(b))
    # exp2_lut[p] = bposit16(2^decoded(p)). Companion to log2_lut.
    # 65 536 × 2 bytes = 128 KB. __device__ const.
    from bposit16_reference import bposit16_exp2 as py_bposit16_exp2
    exp2_lut = [py_bposit16_exp2(i) for i in range(65536)]

    lines.append("// bposit16 exp2 LUT — exp2_lut[p] = bposit16(2^decoded(p))")
    lines.append("// Companion to log2_lut. Together they enable multiply via")
    lines.append("// mul(a, b) = exp2(log2(a) + log2(b)) for positive operands.")
    lines.append("__device__ const std::uint16_t bposit16_exp2_lut_first_half[32768] = {")
    for chunk_start in range(0, 32768, 16):
        chunk = exp2_lut[chunk_start:chunk_start + 16]
        lines.append("    " + ", ".join(f"0x{v:04x}" for v in chunk) + ",")
    lines.append("};")
    lines.append("__device__ const std::uint16_t bposit16_exp2_lut_second_half[32768] = {")
    for chunk_start in range(32768, 65536, 16):
        chunk = exp2_lut[chunk_start:chunk_start + 16]
        lines.append("    " + ", ".join(f"0x{v:04x}" for v in chunk) + ",")
    lines.append("};")
    lines.append("")
    lines.append("__device__ __forceinline__")
    lines.append("std::uint16_t bposit16_exp2_lookup(std::uint16_t x) {")
    lines.append("    return (x < 32768)")
    lines.append("        ? bposit16_exp2_lut_first_half[x]")
    lines.append("        : bposit16_exp2_lut_second_half[x - 32768];")
    lines.append("}")
    lines.append("")

    # ---- BPOSIT16 SQUARE LUT (for Renyi-2 collision entropy) ---------------
    # square_lut[p] = bposit16(p²). 65 536 × 2 bytes = 128 KB. __device__ const.
    # (uses py_bposit16_mul from the module-level import above)
    sq_lut = [py_bposit16_mul(i, i) for i in range(65536)]

    lines.append("// bposit16² LUT — square_lut[p] = bposit16(p · p)")
    lines.append("// Used by Renyi-2 collision entropy: Σ p²")
    lines.append("__device__ const std::uint16_t bposit16_square_lut_first_half[32768] = {")
    for chunk_start in range(0, 32768, 16):
        chunk = sq_lut[chunk_start:chunk_start + 16]
        lines.append("    " + ", ".join(f"0x{v:04x}" for v in chunk) + ",")
    lines.append("};")
    lines.append("__device__ const std::uint16_t bposit16_square_lut_second_half[32768] = {")
    for chunk_start in range(32768, 65536, 16):
        chunk = sq_lut[chunk_start:chunk_start + 16]
        lines.append("    " + ", ".join(f"0x{v:04x}" for v in chunk) + ",")
    lines.append("};")
    lines.append("")
    lines.append("__device__ __forceinline__")
    lines.append("std::uint16_t bposit16_square_lookup(std::uint16_t x) {")
    lines.append("    return (x < 32768)")
    lines.append("        ? bposit16_square_lut_first_half[x]")
    lines.append("        : bposit16_square_lut_second_half[x - 32768];")
    lines.append("}")
    lines.append("")

    # ---- BPOSIT8 LUTs (for MERA contraction) -------------------------------
    # bposit8 only has 256 possible values. Tables are tiny:
    #   to_quire: 256 × 32 bytes = 8 KB
    #   mul_lut:  256 × 256 × 1 byte = 64 KB (perfect for __constant__)
    from bposit16_reference import (  # noqa: E402
        encode_bposit8, decode_bposit8, decoded_to_fraction_8,
        bposit8_mul as py_bposit8_mul, bposit8_to_quire as py_bposit8_to_quire,
        NAR_8 as NAR8,
    )

    lines.append("// ============================================================")
    lines.append("// BPOSIT8 LUTs (for MERA contraction)")
    lines.append("// ============================================================")
    lines.append("")
    lines.append("// bposit8 → quire256 fixed-point (4× uint64). 256 entries × 32 bytes = 8 KB.")
    lines.append("__device__ const std::uint64_t bposit8_to_quire_lut[256][4] = {")
    for i in range(256):
        q = py_bposit8_to_quire(i)
        if q < 0:
            q += (1 << 256)
        words = [(q >> (64 * w)) & 0xFFFFFFFFFFFFFFFF for w in range(4)]
        lines.append(f"    {{0x{words[0]:016x}ull, 0x{words[1]:016x}ull, "
                     f"0x{words[2]:016x}ull, 0x{words[3]:016x}ull}},  // [{i}]")
    lines.append("};")
    lines.append("")

    lines.append("// bposit8 multiplication: mul_lut[a][b] = encoded(decode(a)*decode(b))")
    lines.append("// 256 × 256 × 1 byte = 64 KB — exactly fills __constant__ memory.")
    lines.append("__device__ __constant__ const std::uint8_t bposit8_mul_lut[256][256] = {")
    for a in range(256):
        row = [py_bposit8_mul(a, b) for b in range(256)]
        # Format 16 entries per line
        row_lines = []
        for chunk_start in range(0, 256, 16):
            chunk = row[chunk_start:chunk_start + 16]
            row_lines.append("        " + ", ".join(f"0x{v:02x}" for v in chunk))
        lines.append("    {")
        lines.append(",\n".join(row_lines))
        lines.append("    },")
    lines.append("};")
    lines.append("")
    lines.append("__device__ __forceinline__")
    lines.append("std::uint8_t bposit8_mul_lookup(std::uint8_t a, std::uint8_t b) {")
    lines.append("    return bposit8_mul_lut[a][b];")
    lines.append("}")
    lines.append("")

    lines.append("#endif // MOSYNE_BPOSIT16_LUTS_CUH")

    out_path.write_text("\n".join(lines))
    print(f"wrote {out_path}  ({out_path.stat().st_size:,} bytes)")
    print(f"  valid entries:    {n_valid}")
    print(f"  zero/NaR/special: {n_special}")
    print(f"  negative inputs:  {n_negative}")
    print(f"  spot-checks (encoded log₂):")
    for v in [0.25, 0.5, 1.0, 2.0, 4.0, 0.125, 8.0]:
        bp = encode_bposit16(v)
        log_bp = log2_lut[bp]
        if log_bp == NAR:
            recovered = float("nan")
        else:
            d = decode_bposit16(log_bp)
            recovered = float(decoded_to_fraction(d)) if not d.is_special else float("nan")
        print(f"    log₂({v}) = {math.log2(v):>5.2f}  →  LUT(0x{bp:04x}) = "
              f"0x{log_bp:04x}  →  decoded = {recovered:.4f}")


if __name__ == "__main__":
    main()
