#!/usr/bin/env python3
"""Generate `/tmp/test_quire_to_bp32_cases.h` for test_quire_to_bp32.cu.

Each case carries a quire256 (4× uint64) and the bposit32 the Python
reference encodes from it. The CUDA test runs `quire256_to_bposit32` on
the inputs and asserts bit-exact equality.

Cases cover:
  - Powers of two within bp32's range (must agree bit-exactly with the
    bridge through bposit16 + 16-bit widen, since these are exactly
    representable in bp16)
  - Irrational targets (π, e, sqrt(2), 1.234567891) where the native
    encoder MUST diverge from the bridge by preserving extra
    fraction bits the bridge truncates
  - Edge cases: zero, +/- saturation boundaries
"""
from __future__ import annotations
import sys
from fractions import Fraction
from pathlib import Path

# Make the reference module importable when run from the repo root.
REPO_DEPLOY = Path(__file__).resolve().parent
sys.path.insert(0, str(REPO_DEPLOY))
from bposit16_reference import encode_bposit32, QUIRE_FRAC_BITS  # noqa: E402


def value_to_quire_words(val) -> tuple[int, int, int, int]:
    """Encode a Python number as a 256-bit two's-complement quire (96-bit
    fixed-point fraction window) and return the four uint64 words in
    little-endian order, matching the CUDA `quire256.w[0..3]` layout."""
    f = Fraction(val) if not isinstance(val, Fraction) else val
    q = int(f * (1 << QUIRE_FRAC_BITS))
    if q < 0:
        q = ((1 << 256) + q) & ((1 << 256) - 1)
    return tuple((q >> (64 * i)) & ((1 << 64) - 1) for i in range(4))


CASES: list[tuple[str, object]] = [
    ("zero",                         Fraction(0)),
    ("1.0",                          Fraction(1)),
    ("2.0",                          Fraction(2)),
    ("4.0",                          Fraction(4)),
    ("8.0 (= log2(256), shannon)",   Fraction(8)),
    ("0.5",                          Fraction(1, 2)),
    ("0.25",                         Fraction(1, 4)),
    ("0.125",                        Fraction(1, 8)),
    ("1.5",                          Fraction(3, 2)),
    ("-2.0",                         Fraction(-2)),
    ("-0.25",                        Fraction(-1, 4)),
    ("pi (~3.14159265)",             Fraction(355, 113)),
    ("e (~2.71828183)",              Fraction(193, 71)),
    ("1/3",                          Fraction(1, 3)),
    ("sqrt(2) approx",               Fraction(1414213562, 10**9)),
    ("1.234567891",                  Fraction(1234567891, 10**9)),
    ("0.001",                        Fraction(1, 1000)),
    ("1000.0",                       Fraction(1000)),
    ("max_pos (saturate)",           Fraction(2) ** 49),
    ("min_pos (saturate down)",      Fraction(1, 2 ** 49)),
]


def main() -> None:
    out_path = Path("/tmp/test_quire_to_bp32_cases.h")
    lines = []
    lines.append("// AUTO-GENERATED by gen_test_cases_quire_to_bp32.py — do not edit.")
    lines.append("// quire256 (4× uint64 little-endian) → expected bposit32 (uint32).")
    lines.append("")
    lines.append("struct Case {")
    lines.append("    std::uint64_t w[4];")
    lines.append("    std::uint32_t expected;")
    lines.append("    const char* note;")
    lines.append("};")
    lines.append("")
    lines.append("static const Case cases[] = {")
    for note, val in CASES:
        w = value_to_quire_words(val)
        expected = encode_bposit32(val) & 0xFFFFFFFF
        lines.append(
            f'    {{ {{ 0x{w[0]:016x}ULL, 0x{w[1]:016x}ULL, '
            f'0x{w[2]:016x}ULL, 0x{w[3]:016x}ULL }}, '
            f'0x{expected:08x}U, "{note}" }},'
        )
    lines.append("};")
    out_path.write_text("\n".join(lines) + "\n")
    print(f"wrote {out_path} with {len(CASES)} cases")


if __name__ == "__main__":
    main()
