#!/usr/bin/env python3
# Copyright (c) 2026 Ry Bruscoe and Anomly, Inc.
# SPDX-License-Identifier: Apache-2.0
"""Generate `/tmp/test_add_cases.h` for test_bposit16_add.cu.

Each case carries two bposit16 operands and the bposit16 the Python
reference encodes for `a + b` via the exact quire path
(`bposit16_add` = quire256_to_bposit16(quire(a) + quire(b))). The CUDA
test runs `bposit16_add_dev` and asserts bit-exact equality.

The committed `test_cases_add_inline.h` is an equivalent snapshot the
test includes by default; this generator documents the recipe so the
case set can be regenerated or extended from the Python reference.
"""
from __future__ import annotations
import sys
from fractions import Fraction
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
from bposit16_reference import encode_bposit16, bposit16_add, ZERO, ONE, NAR  # noqa: E402


def bp(v) -> int:
    return encode_bposit16(v) & 0xFFFF


# (note, operand_a, operand_b) — operands are either raw bposit16 ints
# (ZERO/ONE/NAR specials) or ('v', value) pairs encoded through the reference.
CASES = [
    ("1 + 1",            ("v", 1),            ("v", 1)),
    ("2 + 3",            ("v", 2),            ("v", 3)),
    ("0.5 + 0.5",        ("v", Fraction(1, 2)), ("v", Fraction(1, 2))),
    ("0.25 + 0.75",      ("v", Fraction(1, 4)), ("v", Fraction(3, 4))),
    ("-1 + 1",           ("v", -1),           ("v", 1)),
    ("3 + (-1)",         ("v", 3),            ("v", -1)),
    ("-2 + -3",          ("v", -2),           ("v", -3)),
    ("0.1 + 0.2",        ("v", Fraction(1, 10)), ("v", Fraction(1, 5))),
    ("8 + 0.125",        ("v", 8),            ("v", Fraction(1, 8))),
    ("1000 + 1",         ("v", 1000),         ("v", 1)),
    ("0.5 + 0.25",       ("v", Fraction(1, 2)), ("v", Fraction(1, 4))),
    ("zero + 5",         ("raw", ZERO),       ("v", 5)),
    ("5 + zero",         ("v", 5),            ("raw", ZERO)),
    ("nar + 1",          ("raw", NAR),        ("v", 1)),
    ("1 + nar",          ("v", 1),            ("raw", NAR)),
    ("one + one",        ("raw", ONE),        ("raw", ONE)),
]


def resolve(op) -> int:
    kind, val = op
    return val & 0xFFFF if kind == "raw" else bp(val)


def main() -> None:
    out_path = Path("/tmp/test_add_cases.h")
    lines = [
        "// AUTO-GENERATED by gen_test_cases_bposit16_add.py — do not edit.",
        "// bposit16 a, b -> expected bposit16 (a + b via exact quire256).",
        "",
        "struct AddCase {",
        "    std::uint16_t a;",
        "    std::uint16_t b;",
        "    std::uint16_t expected;",
        "    const char* note;",
        "};",
        "",
        "static const AddCase add_cases[] = {",
    ]
    for note, op_a, op_b in CASES:
        a = resolve(op_a)
        b = resolve(op_b)
        expected = bposit16_add(a, b) & 0xFFFF
        lines.append(
            f'    {{ 0x{a:04x}, 0x{b:04x}, 0x{expected:04x}, "{note}" }},'
        )
    lines.append("};")
    out_path.write_text("\n".join(lines) + "\n")
    print(f"wrote {out_path} with {len(CASES)} cases")


if __name__ == "__main__":
    main()
