#!/usr/bin/env python3
# Copyright (c) 2026 Ry Bruscoe and Anomly, Inc.
# SPDX-License-Identifier: Apache-2.0
"""Generate `/tmp/test_mul_cases.h` for test_bposit16_mul.cu.

Each case carries two bposit16 operands and the bposit16 the Python
reference encodes for `a * b` via the **log+exp2** path
(`bposit16_mul_via_log_exp2` — NOT the Fraction-exact `bposit16_mul`).
That is the path `bposit16_mul_dev` implements on device, so this is the
bit-exact comparison the CUDA test asserts.

The committed `test_cases_mul_inline.h` is an equivalent snapshot the
test includes by default; this generator documents the recipe so the
case set can be regenerated or extended from the Python reference.
"""
from __future__ import annotations
import sys
from fractions import Fraction
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
from bposit16_reference import (  # noqa: E402
    encode_bposit16, bposit16_mul_via_log_exp2, ZERO, ONE, NAR,
)


def bp(v) -> int:
    return encode_bposit16(v) & 0xFFFF


CASES = [
    ("2 * 3",            ("v", 2),            ("v", 3)),
    ("0.5 * 4",          ("v", Fraction(1, 2)), ("v", 4)),
    ("-2 * 3",           ("v", -2),           ("v", 3)),
    ("-2 * -2",          ("v", -2),           ("v", -2)),
    ("3 * 3",            ("v", 3),            ("v", 3)),
    ("1.5 * 2",          ("v", Fraction(3, 2)), ("v", 2)),
    ("0.25 * 0.25",      ("v", Fraction(1, 4)), ("v", Fraction(1, 4))),
    ("8 * 0.125",        ("v", 8),            ("v", Fraction(1, 8))),
    ("7 * 1 (one short)", ("v", 7),           ("raw", ONE)),
    ("-0.5 * 0.5",       ("v", Fraction(-1, 2)), ("v", Fraction(1, 2))),
    ("10 * 0.1",         ("v", 10),           ("v", Fraction(1, 10))),
    ("zero * 5",         ("raw", ZERO),       ("v", 5)),
    ("nar * 2",          ("raw", NAR),        ("v", 2)),
    ("one * one",        ("raw", ONE),        ("raw", ONE)),
    ("100 * 0.01",       ("v", 100),          ("v", Fraction(1, 100))),
]


def resolve(op) -> int:
    kind, val = op
    return val & 0xFFFF if kind == "raw" else bp(val)


def main() -> None:
    out_path = Path("/tmp/test_mul_cases.h")
    lines = [
        "// AUTO-GENERATED by gen_test_cases_bposit16_mul.py — do not edit.",
        "// bposit16 a, b -> expected bposit16 (a * b via log2+quire+exp2).",
        "",
        "struct MulCase {",
        "    std::uint16_t a;",
        "    std::uint16_t b;",
        "    std::uint16_t expected;",
        "    const char* note;",
        "};",
        "",
        "static const MulCase mul_cases[] = {",
    ]
    for note, op_a, op_b in CASES:
        a = resolve(op_a)
        b = resolve(op_b)
        expected = bposit16_mul_via_log_exp2(a, b) & 0xFFFF
        lines.append(
            f'    {{ 0x{a:04x}, 0x{b:04x}, 0x{expected:04x}, "{note}" }},'
        )
    lines.append("};")
    out_path.write_text("\n".join(lines) + "\n")
    print(f"wrote {out_path} with {len(CASES)} cases")


if __name__ == "__main__":
    main()
