// shannon_entropy_bposit16.cu — first 5-DST → RTX 5090 kernel.
//
// Spec: 5DST_v2_API_SPEC.h, layer 1 (quantum information):
//     bposit32_t shannon_entropy(const bposit16_t* p, size_t n);
//
// Architectural compliance: ALL computation is integer-only over b-posit
// bit patterns. NO IEEE float/double in the device path. The quire256
// accumulator lives in registers (4× uint64 per thread, reduced across
// the warp via __shfl_down_sync, then across the block via shared
// memory). Final-stage encoding converts the quire to bposit32.
//
// Why this kernel first:
//   - Layer 1 primitive — semantics fully defined by the spec.
//   - No tensor-core ambiguity (it's a reduction, not a GEMM); the same
//     kernel runs unchanged under porting paths A / B / C of
//     docs/research/5dst_blackwell_porting_2026-05-05.md.
//   - Bandwidth-bound; demo number is throughput in GB/s vs HBM peak.
//   - Tiny: ~80 lines of device code; trivially differentially-testable
//     against test_shannon_entropy.cu and the Python reference.
//
// Build:
//     nvcc -O3 -std=c++17 -arch=sm_120 \
//          -shared -Xcompiler -fPIC \
//          shannon_entropy_bposit16.cu -o libshannon_bposit.so
//
// The b-posit primitives are LUT-driven and supplied by bposit16_luts.cuh
// (regenerated by build_bposit_luts.py from bposit16_reference.py — the
// canonical Python reference for the spec). The fused
// bposit16_term_lookup gives p·log₂(p) in one indirection; the
// bposit16_to_quire_lut gives the quire256 fixed-point representation
// in another. test_shannon_entropy.cu validates the same code path
// bit-exactly against the Python reference for n = 4, 1024, 4096.

#include "bposit16_luts.cuh"
#include "bposit16_encode.cuh"   // quire256 struct + q256_add/q256_negate/quire256_to_bposit16

#include <cuda_runtime.h>
#include <cstdint>
#include <cstdio>

using bposit16_t = std::uint16_t;
using bposit32_t = std::uint32_t;

// Per-warp quire reduction via 4× shuffle-down passes (one per uint64 word).
__device__ __forceinline__ quire256 warp_reduce_quire(quire256 q) {
    for (int offset = 16; offset > 0; offset >>= 1) {
        quire256 partner;
        partner.w[0] = __shfl_down_sync(0xffffffff, q.w[0], offset);
        partner.w[1] = __shfl_down_sync(0xffffffff, q.w[1], offset);
        partner.w[2] = __shfl_down_sync(0xffffffff, q.w[2], offset);
        partner.w[3] = __shfl_down_sync(0xffffffff, q.w[3], offset);
        q = q256_add(q, partner);
    }
    return q;
}

constexpr int THREADS_PER_BLOCK = 256;
constexpr int WARPS_PER_BLOCK   = THREADS_PER_BLOCK / 32;

// Block kernel: each thread loads bposit16 probabilities, looks up
// term = bposit16(p · log₂(p)), looks up its quire256 fixed-point, and
// accumulates into a per-thread quire256.
__global__ void shannon_entropy_block_reduce(
    const bposit16_t* __restrict__ p,
    std::size_t n,
    quire256* __restrict__ block_partial)
{
    quire256 acc = q256_zero();

    std::size_t stride = std::size_t(gridDim.x) * blockDim.x;
    std::size_t i      = std::size_t(blockIdx.x) * blockDim.x + threadIdx.x;
    for (; i < n; i += stride) {
        bposit16_t prob = p[i];
        bposit16_t term = bposit16_term_lookup(prob);   // p · log₂(p)
        quire256 term_q;
        term_q.w[0] = bposit16_to_quire_lut[term][0];
        term_q.w[1] = bposit16_to_quire_lut[term][1];
        term_q.w[2] = bposit16_to_quire_lut[term][2];
        term_q.w[3] = bposit16_to_quire_lut[term][3];
        acc = q256_add(acc, term_q);
    }

    acc = warp_reduce_quire(acc);
    int lane = threadIdx.x & 31;
    int warp = threadIdx.x >> 5;

    __shared__ quire256 warp_acc[WARPS_PER_BLOCK];
    if (lane == 0) warp_acc[warp] = acc;
    __syncthreads();

    if (warp == 0) {
        acc = (lane < WARPS_PER_BLOCK) ? warp_acc[lane] : q256_zero();
        acc = warp_reduce_quire(acc);
        if (lane == 0) block_partial[blockIdx.x] = acc;
    }
}

// Final-stage block-of-blocks reduction. Single block; assumes block
// count fits in one warp (≤ 32 partials; the host launcher caps at 32).
// Negates the running sum so we return H = -Σ p·log₂(p), then encodes
// the quire to bposit32 via the canonical quire256_to_bposit16 LUT
// path + the trivial bposit16→bposit32 widening shift (Gustafson 7.4).
__global__ void shannon_entropy_finalize(
    const quire256* __restrict__ block_partial,
    std::size_t num_blocks,
    bposit32_t* __restrict__ out)
{
    quire256 acc = (threadIdx.x < num_blocks) ? block_partial[threadIdx.x]
                                              : q256_zero();
    acc = warp_reduce_quire(acc);
    if (threadIdx.x == 0) {
        // Entropy = -Σ p·log₂(p). quire256_to_bposit32 is the native
        // 31-bit-magnitude encoder (bposit16_encode.cuh), bit-exact
        // against the Python reference's encode_bposit32 for both
        // power-of-two H values and arbitrary distributions.
        acc = q256_negate(acc);
        *out = quire256_to_bposit32(acc);
    }
}

// Host launcher.
extern "C" int shannon_entropy_bposit16_cuda(
    const bposit16_t* d_p, std::size_t n, bposit32_t* d_out)
{
    if (n == 0) return -1;

    constexpr std::size_t ELEMENTS_PER_THREAD = 4096;
    std::size_t num_blocks = (n + (THREADS_PER_BLOCK * ELEMENTS_PER_THREAD) - 1)
                           / (THREADS_PER_BLOCK * ELEMENTS_PER_THREAD);
    if (num_blocks == 0) num_blocks = 1;
    if (num_blocks > 32) num_blocks = 32;  // finalize stage assumes ≤ 32

    quire256* d_partial = nullptr;
    cudaError_t err = cudaMalloc(&d_partial, num_blocks * sizeof(quire256));
    if (err != cudaSuccess) {
        std::fprintf(stderr, "cudaMalloc failed: %s\n", cudaGetErrorString(err));
        return -2;
    }

    shannon_entropy_block_reduce<<<num_blocks, THREADS_PER_BLOCK>>>(d_p, n, d_partial);
    shannon_entropy_finalize<<<1, 32>>>(d_partial, num_blocks, d_out);

    err = cudaGetLastError();
    cudaFree(d_partial);
    return (err == cudaSuccess) ? 0 : -3;
}
