// test_quire_to_bp32.cu — Validate the CUDA quire256_to_bposit32 device
// function against the Python reference's encode_bposit32 (truncate mode,
// the default). Cases generated by gen_test_cases_quire_to_bp32.py.
//
// Build:
//     python3 gen_test_cases_quire_to_bp32.py
//     nvcc -O3 -std=c++17 -gencode arch=compute_86,code=sm_86 \
//          -gencode arch=compute_120,code=sm_120 \
//          test_quire_to_bp32.cu -o test_q2bp32
//     ./test_q2bp32

#include "bposit16_luts.cuh"
#include "bposit16_encode.cuh"

#include <cuda_runtime.h>
#include <cstdint>
#include <cstdio>

__global__ void encode_kernel(const quire256* __restrict__ in,
                              std::uint32_t* __restrict__ out, int n) {
    int idx = blockIdx.x * blockDim.x + threadIdx.x;
    if (idx >= n) return;
    out[idx] = quire256_to_bposit32(in[idx]);
}

int main() {
    using uint64_t = std::uint64_t;
    using uint32_t = std::uint32_t;
    #include "/tmp/test_quire_to_bp32_cases.h"
    constexpr int N = sizeof(cases) / sizeof(cases[0]);

    quire256 h_in[N];
    std::uint32_t h_out[N];
    for (int i = 0; i < N; ++i) {
        h_in[i].w[0] = cases[i].w[0];
        h_in[i].w[1] = cases[i].w[1];
        h_in[i].w[2] = cases[i].w[2];
        h_in[i].w[3] = cases[i].w[3];
    }

    quire256* d_in;
    std::uint32_t* d_out;
    cudaMalloc(&d_in, N * sizeof(quire256));
    cudaMalloc(&d_out, N * sizeof(std::uint32_t));
    cudaMemcpy(d_in, h_in, N * sizeof(quire256), cudaMemcpyHostToDevice);
    encode_kernel<<<1, 32>>>(d_in, d_out, N);
    cudaDeviceSynchronize();
    cudaMemcpy(h_out, d_out, N * sizeof(std::uint32_t), cudaMemcpyDeviceToHost);

    std::printf("=== quire256 -> bposit32 device encoder ===\n\n");
    int pass = 0;
    for (int i = 0; i < N; ++i) {
        bool ok = (h_out[i] == cases[i].expected);
        if (ok) ++pass;
        std::printf("  [%s] got=0x%08x  expected=0x%08x  %s\n",
                    ok ? "PASS" : "FAIL", h_out[i], cases[i].expected,
                    cases[i].note);
    }
    std::printf("\nSummary: %d/%d pass\n", pass, N);

    cudaFree(d_in); cudaFree(d_out);
    return (pass == N) ? 0 : 1;
}
